[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "data_emulator"
version = "0.1"
requires-python = ">=3.10"
dependencies = [
    'sdv==1.4.0',
    'pandas==2.1.0',
    'psycopg2-binary==2.9.7',
]

[tool.setuptools]
py-modules = []
