[default]
sample_db__host = ''
sample_db__port = ''
sample_db__database = ''
sample_db__user = ''
sample_db__password = ''

synthetic_db__host = ''
synthetic_db__port = ''
synthetic_db__database = ''
synthetic_db__user = ''
synthetic_db__password = ''

[testing]
sample_db__host = ''
sample_db__port = '5432'
sample_db__database = 'sample_postgres_db'
sample_db__user = ''
sample_db__password = ''

synthetic_db__host = ''
synthetic_db__port = '5431'
synthetic_db__database = 'synthetic_postgres_db'
synthetic_db__user = ''
synthetic_db__password = ''
